CREATE TABLE CASES (
  ID          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME        VARCHAR(50)  NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL
);

CREATE TABLE USERS (
  ID       INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  ENABLED  BIT         NOT NULL DEFAULT 1
);

CREATE TABLE ATTORNEYS (
  ID        INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME		VARCHAR(50) NOT NULL,
  AGE		INT			NOT NULL,
  GENDER	VARCHAR(50) NOT NULL,
  DEGREE	VARCHAR(50) NOT NULL,
  FEE		INT			NOT NULL,
  USERID  VARCHAR(50) NOT NULL,
  PHONE		VARCHAR(40) NOT NULL,
  EMAIL		VARCHAR(50) NOT NULL,
  ENABLED  BIT         NOT NULL DEFAULT 1
);
ALTER TABLE ATTORNEYS ADD FOREIGN KEY (USERID) REFERENCES USERS (ID);

CREATE TABLE CUSTOMERS (
  ID        INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME  	VARCHAR(50) NOT NULL,
  AGE		INT			NOT NULL,
  GENDER	VARCHAR(50) NOT NULL,
  USERID  VARCHAR(50) NOT NULL,
  PHONE		VARCHAR(40) NOT NULL,
  EMAIL		VARCHAR(50) NOT NULL,
  ENABLED  BIT         NOT NULL DEFAULT 1
);
ALTER TABLE CUSTOMERS ADD FOREIGN KEY (USERID) REFERENCES USERS (ID);

CREATE TABLE HIRING_DETAILS (
  ID              INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ATTORNEY_ID     INT      NOT NULL,
  CUSTOMER_ID     INT      NOT NULL,
  START           DATETIME NOT NULL,
  FINISH          DATETIME,
  CASE_ID		  INT,
  STATUS	  	  VARCHAR(20)
);
ALTER TABLE HIRING_DETAILS ADD FOREIGN KEY (ATTORNEY_ID) REFERENCES ATTORNEYS (ID);
ALTER TABLE HIRING_DETAILS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID);

